Register front
luiscorrea7/StoreApple-FrontEnd pull request #6
Opened 2023-12-27 12:01 UTC by AUGUSTODIAZ1

Estilado Register

2023-12-27 12:52 UTC, AleGalarze21 approved these changes
Cambios Aprobados

2023-12-27 13:10 UTC, luiscorrea7 requested changes
Esperando a resolver conflictos antes del merging

2023-12-28 07:29 UTC, luiscorrea7 approved these changes

2023-12-28 07:37 UTC, luiscorrea7 commented
Cierro pull request con conflictos

2023-12-28 07:37 UTC, closed without merging